name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: zulu
      - name: Compile a first time
        run: sbt compile
      - name: Edit A.scala
        run: sed -i 's/NAME/NAME2/g' src/main/scala/A.scala
      - name: Recompile
        run: sbt compile
